version: '3'

services:
  oi:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
      # wslg
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # wslg
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=$PULSE_SERVER
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    env_file:
      - .env
    ports:
      - 1234:1234
    tty:
      true
    working_dir: /app
