version: '3'

services:
  open-interpreter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root

    tty:
      true

    working_dir: /root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]